name             'mediawiki'
maintainer       'pulsation'
license          'BSD'
description      'Installs/Configures mediawiki'
long_description 'Installs/Configures mediawiki'
version          '0.1.0'

depends          'apache2'
depends          'php'
depends          'mysql'
depends          'database'
